### PR TITLE
Update CocoaPods to v1.0.1 instead of 0.39

### PR DESCRIPTION
**Pull request by dautermann**
If one tries to do a `pod update` (to install Pods) in your Example app directory, you'll likely see this error:

```
myke$ pod update
Update all pods
Re-creating CocoaPods due to major version update.
Setting up CocoaPods master repo
Setup completed
Updating local specs repositories
Analyzing dependencies
[!] The dependency `SnapKit` is not used in any concrete target.
The dependency `Quick` is not used in any concrete target.
The dependency `Nimble` is not used in any concrete target.
```

[It turns out that each Pod requires a target](http://stackoverflow.com/questions/34556991/pod-install-displaying-error-in-cocoapods-version-1-0-0-beta-1).

Changing the Podfile to specify targets for pods results in this:

```
myke$ pod update
Update all pods
Re-creating CocoaPods due to major version update.
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Nimble (4.1.0)
Installing Quick (0.9.2)
Installing SnapKit (0.21.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 3 total pods installed.
```

I also updated the .gitignore file to ignore those pesky `.DS_Store` files.

The project file also got magically regenerated in the process as well.

### CODE REVIEW

**Comment by iwasrobbed** [comment]
Hi @dautermann ! Thanks for the PR! It seems you are using a newer version of CocoaPods (v1.0.1 versus 0.39 that it currently uses in Podfile.lock) which is why it wasn't working for you. I haven't gotten a chance to upgrade just yet, but will look into these changes soon.

My only worry is how many other people are using v1.0.1 and forcing those who are one older versions to upgrade before they can use this pod. I'll ask the CocoaPods team to see if they can provide guidance around adoption rates

**Comment by iwasrobbed** [comment]
(by the way, it appears Travis tests are failing w/ this PR)

**Comment by dautermann** [comment]
I am pretty confident the Podfile will work just fine for 0.39.0 as well (in my day job, I'm regularly jumping between 0.39 and 1.0.1).

And as for Travis, hmmm I've never encountered that.  

When I run tests locally, everything seems to pass:

alltestspassforme
notestsfail

I did just check in a Podfile and Podfile.lock update.

**Comment by dautermann** [comment]
okay, I give up... It's my first time encountering Travis and I simply cannot motivate it to pass, despite following the "`pod install --repo-update`" instructions found [at the end of this post](https://github.com/CocoaPods/CocoaPods/issues/5149#issuecomment-209593537), [making the iOS deployment target matching between Podfile & Project](https://github.com/CocoaPods/CocoaPods/issues/3964#issuecomment-127650211) (8.0) or by downgrading my local Cocoapods to 0.39 (the Podfile still appears to work fine and tests run as well).

**Comment by iwasrobbed** [comment]
@dautermann No worries, I'll look into this soon. For now, you can just point your pod install to your forked repo. Thanks again!

**Pull request closed without merging**
