### PR TITLE
Swift 4.2 Migration

### PR DESCRIPTION
**Pull request by alex-taffe**
I'm not sure I got everything in terms of updating the pod spec and similar files, but everything seems to work

### CODE REVIEW

**Review by iwasrobbed — CHANGES_REQUESTED** [review]
Looks great overall! I'll test locally just to be sure, but I think you just need a quick change to `.travis.yml` file to use Xcode 10

https://github.com/iwasrobbed/RPCircularProgress/blob/master/.travis.yml#L1 (e.g. https://blog.travis-ci.com/2018-08-16-xcode-10-beta-is-now-available)

**Comment by alex-taffe** [comment]
Ohh good point, I’ll check that out. Also should the version number ?e 0.4.2 or 0.4.1? @iwasrobbed

**Comment by alex-taffe** [comment]
@iwasrobbed it seems like Nimble is failing to build, suggestions?

**Comment by iwasrobbed** [comment]
Likely just need to update Nimble's version since I imagine they had to
update it for 4.2 as well

Also, re: version: what you had was fine (hotfix bump)

**Comment by alex-taffe** [comment]
I'm an idiot, nice catch @iwasrobbed, should be good to go now

**Comment by iwasrobbed** [comment]
Perfect, thanks again @alex-taffe !! 🙌

**Comment by iwasrobbed** [comment]
Just pushed an updated podspec to CocoaPods as `v0.4.1` 👍

**Pull request merged**
