### PR TITLE
Fixed continuous 20% CPU load (tested on iPad 3)

### PR DESCRIPTION
**Pull request by Uniprog**
Hi Rob,
Without this fix I have continuously 20% CPU load on iPad 3. With fix 0%. Could you check please.
Thanks

### CODE REVIEW

**Comment by iwasrobbed** [comment]
@Uniprog Can you replicate this issue with the example app included in the repo? (e.g. check cpu load *on device* only, not on the simulator)

**Comment by Uniprog** [comment]
I tested on iPad 3 iOS 9.3.5(13G36) real device. And without fix I had 20-22% CPU load. This because animation continuously calling draw rect method. But with fix I had 0% CPU and no  continuously calling draw rect.

**Comment by iwasrobbed** [comment]
@Uniprog Looks like this is failing a test. I have not had time to review w/ the example app on a device, so I'd advise just using your fork for the immediate future as this seems like a significant change.

**Comment by iwasrobbed** [comment]
Closing since I have not heard back

**Pull request closed without merging**
